# ref: https://github.com/actions/runner-images
name: amd64 MacOS Bazel

on: [push, pull_request, workflow_dispatch]

# Building using the github runner environement directly.
jobs:
  native:
    strategy:
      matrix:
        python: [
          {version: '3.9'},
          #{version: '3.10'},
          #{version: '3.11'},
          {version: '3.12'},
        ]
      fail-fast: false
    name: MacOS•Bazel•Py${{ matrix.python.version }}
    runs-on: macos-13 # last macos intel based runner
    steps:
      - uses: actions/checkout@v4
      - name: Set Java to OpenJDK 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python.version }}
      - name: Check Python
        run: |
          python --version
          python -m platform
      - name: Check Bazel
        run: bazel version
      - name: Build
        run: >
          bazel build
          -c opt
          --subcommands=pretty_print
          --enable_bzlmod
          //...
      - name: Test
        run: >
          bazel test
          -c opt
          --test_output=all
          --subcommands=pretty_print
          --enable_bzlmod
          //...

  amd64_macos_bazel:
    runs-on: ubuntu-latest
    needs: native
    steps:
      - uses: actions/checkout@v4
